services:
  postgres:
    image: postgres:16
    container_name: aloqa-postgres
    environment:
      POSTGRES_DB: aloqa
      POSTGRES_USER: aloqa
      POSTGRES_PASSWORD: aloqa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
